name: Bonjour
on:
  - push
jobs:
  dire_bonjour:
    runs-on: ubuntu-latest
    container: 
      image: ghcr.io/cicd-lectures/gitpod:latest
      options: --user=root
    steps:
      - uses: actions/checkout@v2 
      - run: | 
          sudo apt-get update 
          sudo apt-get install -y cowsay
      - run: ls -l # Liste les fichier du répertoire courant
      - run: cat README.md | cowsay # Affiche le contenu du fichier `README.md` à la base du dépôt
  run-maven:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu' # See 'Supported distributions' for available options
        java-version: '11'
    - run: java -version
    - run: mvn -version
    - run: mvn help:effective-pom 
