name: ci
on:
  
  push:
    branches:
      - main
    tags:
      - v*
  - pull-request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu' # See 'Supported distributions' for available options
        java-version: '11'
    - run: mvn package
    - uses: actions/upload-artifact@v2
      with:
        name: menu-server.jar
        path: target/menu-server.jar  
jobs:
  release-heroku:
    steps:
    - uses: actions/upload-artifact@v2
      with:
        name: menu-server.jar
        path: target/menu-server.jar
    - uses: actions/checkout@v2
    - shell: bash
      env:
        HEROKU_API_KEY : ${{secrets.HEROKU_API_KEY}}
    - run: |
        heroku login
        heroku container:release web --app menu-server-herman-mohad



